// delete
export var INDEX_DELETE = 'INDEX_DELETE';
export var DETAIL_DELETE = 'DETAIL_DELETE';
export var DETAIL_DELETE_FROM_DETAIL_PAGE = 'DETAIL_DELETE_FROM_DETAIL_PAGE';
export var DELETE_WARNING = 'DELETE_WARNING';
export var CANCEL_DELETE = 'CANCEL_DELETE'; // edit

export var TABLE_ROW_EDIT = 'TABLE_ROW_EDIT';
export var ATTRIBUTE_EDIT = 'ATTRIBUTE_EDIT';
export var TABLE_EDIT_CANCEL = 'TABLE_EDIT_CANCEL';
export var ATTRIBUTE_EDIT_CANCEL = 'ATTRIBUTE_EDIT_CANCEL';
export var INDEX_EDIT_SUBMIT = 'INDEX_EDIT_SUBMIT';
export var DETAIL_TABLE_EDIT_SUBMIT = 'DETAIL_TABLE_EDIT_SUBMIT';
export var DETAIL_ATTRIBUTE_SUBMIT = 'DETAIL_ATTRIBUTE_SUBMIT';
export var EDIT_INPUT_CHANGE = 'EDIT_INPUT_CHANGE';
export var FILE_SUBMIT = 'FILE_SUBMIT'; // input

export var MENU_OPEN = 'MENU_OPEN'; // create

export var INPUT_CHANGE = 'INPUT_CHANGE';
export var CANCEL = 'CANCEL';
export var SAVE = 'SAVE';
export var SAVE_SUCCESSFUL = 'SAVE_SUCCESSFUL';
export var STACK_CREATE = 'STACK_CREATE';
export var DETAIL_CREATE = 'DETAIL_CREATE';
export var INDEX_CREATE = 'INDEX_CREATE';
export var BREADCRUMB_CLICK = 'BREADCRUMB_CLICK'; // tooltip

export var TOOLTIP_OPEN = 'TOOLTIP_OPEN';
export var FETCH_MODEL_TOOLTIP = 'FETCH_MODEL_TOOLTIP';
export var UPDATE_MODEL_TOOLTIP = 'UPDATE_MODEL_TOOLTIP'; // tableView

export var INDEX_ADD_FILTER = 'INDEX_ADD_FILTER';
export var INDEX_CLEAR_FILTERS = 'INDEX_CLEAR_FILTERS';
export var INDEX_CHANGE_FILTER_FIELD = 'INDEX_CHANGE_FILTER_FIELD';
export var INDEX_DELETE_FILTER = 'INDEX_DELETE_FILTER';
export var INDEX_TABLE_FILTER_CHANGE = 'INDEX_TABLE_FILTER_CHANGE';
export var INDEX_TABLE_FILTER_DROPDOWN = 'INDEX_TABLE_FILTER_DROPDOWN';
export var INDEX_TABLE_FILTER_SUBMIT = 'INDEX_TABLE_FILTER_SUBMIT';
export var INDEX_TABLE_SORT_CHANGE = 'INDEX_TABLE_SORT_CHANGE';
export var HIDE_TABLE_CHANGE = 'HIDE_TABLE_CHANGE'; // epics

export var FETCH_MODEL_INDEX = 'FETCH_MODEL_INDEX';
export var FETCH_MODEL_DETAIL = 'FETCH_MODEL_DETAIL';
export var CHANGE_PAGE = 'CHANGE_PAGE'; // model

export var UPDATE_MODEL_DETAIL = 'UPDATE_MODEL_DETAIL';
export var UPDATE_MODEL_INDEX = 'UPDATE_MODEL_INDEX'; // logger

export var ERROR_LOGGER = 'ERROR_LOGGER';