// delete
export var UPDATE_DELETE_DETAIL = 'UPDATE_DELETE_DETAIL';
export var FETCH_DELETE_DETAIL = 'FETCH_DELETE_DETAIL';
export var CANCEL_DELETE_DETAIL = 'CANCEL_DELETE_DETAIL'; // edit

export var TABLE_ROW_EDIT = 'TABLE_ROW_EDIT';
export var ATTRIBUTE_EDIT = 'ATTRIBUTE_EDIT';
export var TABLE_EDIT_CANCEL = 'TABLE_EDIT_CANCEL';
export var ATTRIBUTE_EDIT_CANCEL = 'ATTRIBUTE_EDIT_CANCEL';
export var INDEX_EDIT_SUBMIT = 'INDEX_EDIT_SUBMIT';
export var DETAIL_TABLE_EDIT_SUBMIT = 'DETAIL_TABLE_EDIT_SUBMIT';
export var DETAIL_ATTRIBUTE_EDIT_SUBMIT = 'DETAIL_ATTRIBUTE_EDIT_SUBMIT';
export var EDIT_INPUT_CHANGE = 'EDIT_INPUT_CHANGE';
export var INLINE_FILE_SUBMIT = 'INLINE_FILE_SUBMIT';
export var INLINE_FILE_DELETE = 'INLINE_FILE_DELETE';
export var VALIDATION_ERROR_EDIT = 'VALIDATION_ERROR_EDIT';
export var VALIDATION_ERROR_TABLE_ROW = 'VALIDATION_ERROR_TABLE_ROW';
export var DETAIL_TABLE_REMOVE_SUBMIT = 'DETAIL_TABLE_REMOVE_SUBMIT'; // create

export var CREATE_INPUT_CHANGE = 'CREATE_INPUT_CHANGE';
export var CANCEL_CREATE = 'CANCEL_CREATE';
export var SAVE_CREATE = 'SAVE_CREATE';
export var SAVE_CREATE_SUCCESSFUL = 'SAVE_CREATE_SUCCESSFUL';
export var STACK_CREATE = 'STACK_CREATE';
export var DETAIL_CREATE = 'DETAIL_CREATE';
export var INDEX_CREATE = 'INDEX_CREATE';
export var UPDATE_FORM_STACK_INDEX = 'UPDATE_FORM_STACK_INDEX';
export var VALIDATION_ERROR_CREATE = 'VALIDATION_ERROR_CREATE'; // tooltip

export var TOOLTIP_OPEN = 'TOOLTIP_OPEN';
export var FETCH_MODEL_TOOLTIP = 'FETCH_MODEL_TOOLTIP';
export var UPDATE_MODEL_TOOLTIP = 'UPDATE_MODEL_TOOLTIP'; // tableView

export var CHANGE_PAGE = 'CHANGE_PAGE';
export var INDEX_ADD_FILTER = 'INDEX_ADD_FILTER';
export var INDEX_CLEAR_FILTERS = 'INDEX_CLEAR_FILTERS';
export var INDEX_CHANGE_FILTER_FIELD = 'INDEX_CHANGE_FILTER_FIELD';
export var INDEX_DELETE_FILTER = 'INDEX_DELETE_FILTER';
export var INDEX_TABLE_FILTER_CHANGE = 'INDEX_TABLE_FILTER_CHANGE';
export var INDEX_TABLE_FILTER_DROPDOWN = 'INDEX_TABLE_FILTER_DROPDOWN';
export var INDEX_TABLE_FILTER_SUBMIT = 'INDEX_TABLE_FILTER_SUBMIT';
export var INDEX_TABLE_SORT_CHANGE = 'INDEX_TABLE_SORT_CHANGE';
export var COLLAPSE_TABLE_CHANGE = 'COLLAPSE_TABLE_CHANGE';
export var UPDATE_OVERVIEW_DISPLAYED = 'UPDATE_OVERVIEW_DISPLAYED';
export var UPDATE_OVERVIEW_SELECTED = 'UPDATE_OVERVIEW_SELECTED';
export var CHANGE_REL_TABLE_PAGE = 'CHANGE_REL_TABLE_PAGE'; // model

export var FETCH_MODEL_INDEX = 'FETCH_MODEL_INDEX';
export var FETCH_MODEL_DETAIL = 'FETCH_MODEL_DETAIL';
export var UPDATE_MODEL_DETAIL = 'UPDATE_MODEL_DETAIL';
export var UPDATE_MODEL_INDEX = 'UPDATE_MODEL_INDEX';
export var REQUEST_DELETE_MODEL = 'REQUEST_DELETE_MODEL';
export var UPDATE_DELETE_MODEL = 'UPDATE_DELETE_MODEL';
export var REQUEST_DELETE_REL_TABLE_MODEL = 'REQUEST_DELETE_REL_TABLE_MODEL';
export var REQUEST_DELETE_MODEL_FROM_DETAIL_PAGE = 'REQUEST_DELETE_MODEL_FROM_DETAIL_PAGE';
export var REMOVE_INSTANCE = 'REMOVE_INSTANCE'; // search

export var FETCH_SEARCH_ENTRIES = 'FETCH_SEARCH_ENTRIES';
export var UPDATE_SEARCH_ENTRIES = 'UPDATE_SEARCH_ENTRIES';
export var SEARCH_QUERY_TEXT_CHANGED = 'SEARCH_QUERY_TEXT_CHANGED';
export var SEARCH_QUERY_LINK_CLICKED = 'SEARCH_QUERY_LINK_CLICKED';
export var SEARCH_BLUR = 'SEARCH_BLUR';
export var TRIGGER_SEARCH = 'TRIGGER_SEARCH'; // options

export var DATA_OPTIONS_UPDATE = 'DATA_OPTIONS_UPDATE';
export var EXISTING_VALUE_UPDATE = 'EXISTING_VALUE_UPDATE';
export var MENU_OPEN = 'MENU_OPEN';
export var QUERY_SELECT_MENU_OPEN = 'QUERY_SELECT_MENU_OPEN';
export var RELATIONSHIP_SELECT_MENU_OPEN = 'RELATIONSHIP_SELECT_MENU_OPEN'; // alerts

export var ADD_DANGER_ALERT = 'ADD_DANGER_ALERT';
export var ADD_SUCCESS_ALERT = 'ADD_SUCCESS_ALERT'; // validation

export var SAVE_CREATE_CHECK = 'SAVE_CREATE_CHECK';
export var DETAIL_ATTRIBUTE_EDIT_SUBMIT_CHECK = 'DETAIL_ATTRIBUTE_EDIT_SUBMIT_CHECK';
export var DETAIL_TABLE_EDIT_SUBMIT_CHECK = 'DETAIL_TABLE_EDIT_SUBMIT_CHECK';
export var INDEX_EDIT_SUBMIT_CHECK = 'INDEX_EDIT_SUBMIT_CHECK'; // misc

export var UNIQUE_CONSTRAINT = 'UNIQUE_CONSTRAINT';
export var INCORRECT_REQUIREMENT_JMET_TYPE = 'INCORRECT_REQUIREMENT_JMET_TYPE';
export var INCORRECT_REQUIREMENT_PARENT_TYPE = 'INCORRECT_REQUIREMENT_PARENT_TYPE';
export var INCORRECT_DATA_SOURCE_SYSTEM_TYPE = 'INCORRECT_DATA_SOURCE_SYSTEM_TYPE';
export var CREATE_FILE = 'CREATE_FILE';
export var DELETE_FILE = 'DELETE_FILE';