// delete
export var INDEX_DELETE = 'INDEX_DELETE';
export var DETAIL_DELETE = 'DETAIL_DELETE';
export var DETAIL_DELETE_FROM_DETAIL_PAGE = 'DETAIL_DELETE_FROM_DETAIL_PAGE';
export var DELETE_WARNING = 'DELETE_WARNING';
export var CANCEL_DELETE = 'CANCEL_DELETE'; // edit

export var TABLE_ROW_EDIT = 'TABLE_ROW_EDIT';
export var ATTRIBUTE_EDIT = 'ATTRIBUTE_EDIT';
export var TABLE_EDIT_CANCEL = 'TABLE_EDIT_CANCEL';
export var ATTRIBUTE_EDIT_CANCEL = 'ATTRIBUTE_EDIT_CANCEL';
export var INDEX_EDIT_SUBMIT = 'INDEX_EDIT_SUBMIT';
export var DETAIL_TABLE_EDIT_SUBMIT = 'DETAIL_TABLE_EDIT_SUBMIT';
export var DETAIL_ATTRIBUTE_SUBMIT = 'DETAIL_ATTRIBUTE_SUBMIT';
export var EDIT_INPUT_CHANGE = 'EDIT_INPUT_CHANGE';
export var FILE_SUBMIT = 'FILE_SUBMIT'; // create

export var INPUT_CHANGE = 'INPUT_CHANGE';
export var CANCEL = 'CANCEL';
export var SAVE = 'SAVE';
export var SAVE_SUCCESSFUL = 'SAVE_SUCCESSFUL';
export var STACK_CREATE = 'STACK_CREATE';
export var DETAIL_CREATE = 'DETAIL_CREATE';
export var INDEX_CREATE = 'INDEX_CREATE';
export var BREADCRUMB_CLICK = 'BREADCRUMB_CLICK'; // tooltip

export var TOOLTIP_OPEN = 'TOOLTIP_OPEN';
export var FETCH_MODEL_TOOLTIP = 'FETCH_MODEL_TOOLTIP';
export var UPDATE_MODEL_TOOLTIP = 'UPDATE_MODEL_TOOLTIP'; // tableView

export var CHANGE_PAGE = 'CHANGE_PAGE';
export var INDEX_ADD_FILTER = 'INDEX_ADD_FILTER';
export var INDEX_CLEAR_FILTERS = 'INDEX_CLEAR_FILTERS';
export var INDEX_CHANGE_FILTER_FIELD = 'INDEX_CHANGE_FILTER_FIELD';
export var INDEX_DELETE_FILTER = 'INDEX_DELETE_FILTER';
export var INDEX_TABLE_FILTER_CHANGE = 'INDEX_TABLE_FILTER_CHANGE';
export var INDEX_TABLE_FILTER_DROPDOWN = 'INDEX_TABLE_FILTER_DROPDOWN';
export var INDEX_TABLE_FILTER_SUBMIT = 'INDEX_TABLE_FILTER_SUBMIT';
export var INDEX_TABLE_SORT_CHANGE = 'INDEX_TABLE_SORT_CHANGE';
export var COLLAPSE_TABLE_CHANGE = 'COLLAPSE_TABLE_CHANGE';
export var UPDATE_OVERVIEW_DISPLAYED = 'UPDATE_OVERVIEW_DISPLAYED';
export var UPDATE_OVERVIEW_SELECTED = 'UPDATE_OVERVIEW_SELECTED';
export var CHANGE_REL_TABLE_PAGE = 'CHANGE_REL_TABLE_PAGE'; // model

export var FETCH_MODEL_INDEX = 'FETCH_MODEL_INDEX';
export var FETCH_MODEL_DETAIL = 'FETCH_MODEL_DETAIL';
export var UPDATE_MODEL_DETAIL = 'UPDATE_MODEL_DETAIL';
export var UPDATE_MODEL_INDEX = 'UPDATE_MODEL_INDEX'; // search

export var FETCH_SEARCH_ENTRIES = 'FETCH_SEARCH_ENTRIES';
export var UPDATE_SEARCH_ENTRIES = 'UPDATE_SEARCH_ENTRIES';
export var SEARCH_QUERY_TEXT_CHANGED = 'SEARCH_QUERY_TEXT_CHANGED';
export var SEARCH_QUERY_LINK_CLICKED = 'SEARCH_QUERY_LINK_CLICKED';
export var SEARCH_BLUR = 'SEARCH_BLUR';
export var TRIGGER_SEARCH = 'TRIGGER_SEARCH'; // options

export var DATA_OPTIONS_UPDATE = 'DATA_OPTIONS_UPDATE';
export var EXISTING_VALUE_UPDATE = 'EXISTING_VALUE_UPDATE';
export var MENU_OPEN = 'MENU_OPEN';
export var QUERY_SELECT_MENU_OPEN = 'QUERY_SELECT_MENU_OPEN';
export var RELATIONSHIP_SELECT_MENU_OPEN = 'RELATIONSHIP_SELECT_MENU_OPEN'; // alerts

export var ADD_DANGER_ALERT = 'ADD_DANGER_ALERT';