// delete

export const INDEX_DELETE = 'INDEX_DELETE'
export const DETAIL_DELETE = 'DETAIL_DELETE'
export const DETAIL_DELETE_FROM_DETAIL_PAGE = 'DETAIL_DELETE_FROM_DETAIL_PAGE'
export const DELETE_WARNING = 'DELETE_WARNING'
export const CANCEL_DELETE = 'CANCEL_DELETE'

// edit

export const TABLE_ROW_EDIT = 'TABLE_ROW_EDIT'
export const ATTRIBUTE_EDIT = 'ATTRIBUTE_EDIT'
export const TABLE_EDIT_CANCEL = 'TABLE_EDIT_CANCEL'
export const ATTRIBUTE_EDIT_CANCEL = 'ATTRIBUTE_EDIT_CANCEL'
export const INDEX_EDIT_SUBMIT = 'INDEX_EDIT_SUBMIT'
export const DETAIL_TABLE_EDIT_SUBMIT = 'DETAIL_TABLE_EDIT_SUBMIT'
export const DETAIL_ATTRIBUTE_SUBMIT = 'DETAIL_ATTRIBUTE_SUBMIT'
export const EDIT_INPUT_CHANGE = 'EDIT_INPUT_CHANGE'
export const FILE_SUBMIT = 'FILE_SUBMIT'
export const VALIDATION_ERROR_EDIT = 'VALIDATION_ERROR_EDIT'
export const VALIDATION_ERROR_TABLE_ROW = 'VALIDATION_ERROR_TABLE_ROW'

// create

export const CREATE_INPUT_CHANGE = 'CREATE_INPUT_CHANGE'
export const CANCEL_CREATE = 'CANCEL_CREATE'
export const SAVE_CREATE = 'SAVE_CREATE'
export const SAVE_CREATE_SUCCESSFUL = 'SAVE_CREATE_SUCCESSFUL'
export const STACK_CREATE = 'STACK_CREATE'
export const DETAIL_CREATE = 'DETAIL_CREATE'
export const INDEX_CREATE = 'INDEX_CREATE'
export const UPDATE_FORM_STACK_INDEX = 'UPDATE_FORM_STACK_INDEX'
export const VALIDATION_ERROR_CREATE = 'VALIDATION_ERROR_CREATE'

// tooltip

export const TOOLTIP_OPEN = 'TOOLTIP_OPEN'
export const FETCH_MODEL_TOOLTIP = 'FETCH_MODEL_TOOLTIP'
export const UPDATE_MODEL_TOOLTIP = 'UPDATE_MODEL_TOOLTIP'

// tableView

export const CHANGE_PAGE = 'CHANGE_PAGE'
export const INDEX_ADD_FILTER = 'INDEX_ADD_FILTER'
export const INDEX_CLEAR_FILTERS = 'INDEX_CLEAR_FILTERS'
export const INDEX_CHANGE_FILTER_FIELD = 'INDEX_CHANGE_FILTER_FIELD'
export const INDEX_DELETE_FILTER = 'INDEX_DELETE_FILTER'
export const INDEX_TABLE_FILTER_CHANGE = 'INDEX_TABLE_FILTER_CHANGE'
export const INDEX_TABLE_FILTER_DROPDOWN = 'INDEX_TABLE_FILTER_DROPDOWN'
export const INDEX_TABLE_FILTER_SUBMIT = 'INDEX_TABLE_FILTER_SUBMIT'
export const INDEX_TABLE_SORT_CHANGE = 'INDEX_TABLE_SORT_CHANGE'
export const COLLAPSE_TABLE_CHANGE = 'COLLAPSE_TABLE_CHANGE'
export const UPDATE_OVERVIEW_DISPLAYED = 'UPDATE_OVERVIEW_DISPLAYED'
export const UPDATE_OVERVIEW_SELECTED = 'UPDATE_OVERVIEW_SELECTED'
export const CHANGE_REL_TABLE_PAGE = 'CHANGE_REL_TABLE_PAGE'

// model

export const FETCH_MODEL_INDEX = 'FETCH_MODEL_INDEX'
export const FETCH_MODEL_DETAIL = 'FETCH_MODEL_DETAIL'
export const UPDATE_MODEL_DETAIL = 'UPDATE_MODEL_DETAIL'
export const UPDATE_MODEL_INDEX = 'UPDATE_MODEL_INDEX'

// search

export const FETCH_SEARCH_ENTRIES = 'FETCH_SEARCH_ENTRIES'
export const UPDATE_SEARCH_ENTRIES = 'UPDATE_SEARCH_ENTRIES'
export const SEARCH_QUERY_TEXT_CHANGED = 'SEARCH_QUERY_TEXT_CHANGED'
export const SEARCH_QUERY_LINK_CLICKED = 'SEARCH_QUERY_LINK_CLICKED'
export const SEARCH_BLUR = 'SEARCH_BLUR'
export const TRIGGER_SEARCH = 'TRIGGER_SEARCH'

// options

export const DATA_OPTIONS_UPDATE = 'DATA_OPTIONS_UPDATE'
export const EXISTING_VALUE_UPDATE = 'EXISTING_VALUE_UPDATE'
export const MENU_OPEN = 'MENU_OPEN'
export const QUERY_SELECT_MENU_OPEN = 'QUERY_SELECT_MENU_OPEN'
export const RELATIONSHIP_SELECT_MENU_OPEN = 'RELATIONSHIP_SELECT_MENU_OPEN'

// alerts

export const ADD_DANGER_ALERT = 'ADD_DANGER_ALERT'
