
// delete

export const INDEX_DELETE = 'INDEX_DELETE'
export const DETAIL_DELETE = 'DETAIL_DELETE'
export const DETAIL_DELETE_FROM_DETAIL_PAGE = 'DETAIL_DELETE_FROM_DETAIL_PAGE'
export const DELETE_WARNING = 'DELETE_WARNING'
export const CANCEL_DELETE = 'CANCEL_DELETE'

// edit

export const TABLE_ROW_EDIT = 'TABLE_ROW_EDIT'
export const ATTRIBUTE_EDIT = 'ATTRIBUTE_EDIT'
export const TABLE_EDIT_CANCEL = 'TABLE_EDIT_CANCEL'
export const ATTRIBUTE_EDIT_CANCEL = 'ATTRIBUTE_EDIT_CANCEL'
export const INDEX_EDIT_SUBMIT = 'INDEX_EDIT_SUBMIT'
export const DETAIL_TABLE_EDIT_SUBMIT = 'DETAIL_TABLE_EDIT_SUBMIT'
export const DETAIL_ATTRIBUTE_SUBMIT = 'DETAIL_ATTRIBUTE_SUBMIT'
export const EDIT_INPUT_CHANGE = 'EDIT_INPUT_CHANGE'
export const FILE_SUBMIT = 'FILE_SUBMIT'

// input

export const MENU_OPEN = 'MENU_OPEN'

// create

export const INPUT_CHANGE = 'INPUT_CHANGE'
export const CANCEL = 'CANCEL'
export const SAVE = 'SAVE'
export const STACK_CREATE = 'STACK_CREATE'
export const DETAIL_CREATE = 'DETAIL_CREATE'
export const INDEX_CREATE = 'INDEX_CREATE'
export const BREADCRUMB_CLICK = 'BREADCRUMB_CLICK'

// tooltip

export const TOOLTIP_OPEN = 'TOOLTIP_OPEN'
