// delete

export const INDEX_DELETE = 'INDEX_DELETE'
export const DETAIL_DELETE = 'DETAIL_DELETE'
export const DETAIL_DELETE_FROM_DETAIL_PAGE = 'DETAIL_DELETE_FROM_DETAIL_PAGE'
export const DELETE_WARNING = 'DELETE_WARNING'
export const CANCEL_DELETE = 'CANCEL_DELETE'

// edit

export const TABLE_ROW_EDIT = 'TABLE_ROW_EDIT'
export const ATTRIBUTE_EDIT = 'ATTRIBUTE_EDIT'
export const TABLE_EDIT_CANCEL = 'TABLE_EDIT_CANCEL'
export const ATTRIBUTE_EDIT_CANCEL = 'ATTRIBUTE_EDIT_CANCEL'
export const INDEX_EDIT_SUBMIT = 'INDEX_EDIT_SUBMIT'
export const DETAIL_TABLE_EDIT_SUBMIT = 'DETAIL_TABLE_EDIT_SUBMIT'
export const DETAIL_ATTRIBUTE_SUBMIT = 'DETAIL_ATTRIBUTE_SUBMIT'
export const EDIT_INPUT_CHANGE = 'EDIT_INPUT_CHANGE'
export const FILE_SUBMIT = 'FILE_SUBMIT'

// create

export const INPUT_CHANGE = 'INPUT_CHANGE'
export const CANCEL = 'CANCEL'
export const SAVE = 'SAVE'
export const SAVE_SUCCESSFUL = 'SAVE_SUCCESSFUL'
export const STACK_CREATE = 'STACK_CREATE'
export const DETAIL_CREATE = 'DETAIL_CREATE'
export const INDEX_CREATE = 'INDEX_CREATE'
export const BREADCRUMB_CLICK = 'BREADCRUMB_CLICK'

// tooltip

export const TOOLTIP_OPEN = 'TOOLTIP_OPEN'
export const FETCH_MODEL_TOOLTIP = 'FETCH_MODEL_TOOLTIP'
export const UPDATE_MODEL_TOOLTIP = 'UPDATE_MODEL_TOOLTIP'

// tableView

export const INDEX_ADD_FILTER = 'INDEX_ADD_FILTER'
export const INDEX_CLEAR_FILTERS = 'INDEX_CLEAR_FILTERS'
export const INDEX_CHANGE_FILTER_FIELD = 'INDEX_CHANGE_FILTER_FIELD'
export const INDEX_DELETE_FILTER = 'INDEX_DELETE_FILTER'
export const INDEX_TABLE_FILTER_CHANGE = 'INDEX_TABLE_FILTER_CHANGE'
export const INDEX_TABLE_FILTER_DROPDOWN = 'INDEX_TABLE_FILTER_DROPDOWN'
export const INDEX_TABLE_FILTER_SUBMIT = 'INDEX_TABLE_FILTER_SUBMIT'
export const INDEX_TABLE_SORT_CHANGE = 'INDEX_TABLE_SORT_CHANGE'
export const HIDE_TABLE_CHANGE = 'HIDE_TABLE_CHANGE'
export const CHANGE_PAGE = 'CHANGE_PAGE'

// model

export const FETCH_MODEL_INDEX = 'FETCH_MODEL_INDEX'
export const FETCH_MODEL_DETAIL = 'FETCH_MODEL_DETAIL'
export const UPDATE_MODEL_DETAIL = 'UPDATE_MODEL_DETAIL'
export const UPDATE_MODEL_INDEX = 'UPDATE_MODEL_INDEX'

// search

export const FETCH_SEARCH_ENTRIES = 'FETCH_SEARCH_ENTRIES'
export const UPDATE_SEARCH_ENTRIES = 'UPDATE_SEARCH_ENTRIES'
export const SEARCH_QUERY_TEXT_CHANGED = 'SEARCH_QUERY_TEXT_CHANGED'
export const SEARCH_QUERY_LINK_CLICKED = 'SEARCH_QUERY_LINK_CLICKED'
export const SEARCH_BLUR = 'SEARCH_BLUR'
export const TRIGGER_SEARCH = 'TRIGGER_SEARCH'
