// delete

export const UPDATE_DELETE_DETAIL = 'UPDATE_DELETE_DETAIL'
export const FETCH_DELETE_DETAIL = 'FETCH_DELETE_DETAIL'
export const CANCEL_DELETE_DETAIL = 'CANCEL_DELETE_DETAIL'

// edit

export const TABLE_ROW_EDIT = 'TABLE_ROW_EDIT'
export const ATTRIBUTE_EDIT = 'ATTRIBUTE_EDIT'
export const TABLE_EDIT_CANCEL = 'TABLE_EDIT_CANCEL'
export const ATTRIBUTE_EDIT_CANCEL = 'ATTRIBUTE_EDIT_CANCEL'
export const INDEX_EDIT_SUBMIT = 'INDEX_EDIT_SUBMIT'
export const DETAIL_TABLE_EDIT_SUBMIT = 'DETAIL_TABLE_EDIT_SUBMIT'
export const DETAIL_ATTRIBUTE_EDIT_SUBMIT = 'DETAIL_ATTRIBUTE_EDIT_SUBMIT'
export const EDIT_INPUT_CHANGE = 'EDIT_INPUT_CHANGE'
export const INLINE_FILE_SUBMIT = 'INLINE_FILE_SUBMIT'
export const INLINE_FILE_DELETE = 'INLINE_FILE_DELETE'
export const VALIDATION_ERROR_EDIT = 'VALIDATION_ERROR_EDIT'
export const VALIDATION_ERROR_TABLE_ROW = 'VALIDATION_ERROR_TABLE_ROW'
export const DETAIL_TABLE_REMOVE_SUBMIT = 'DETAIL_TABLE_REMOVE_SUBMIT'

// create

export const CREATE_INPUT_CHANGE = 'CREATE_INPUT_CHANGE'
export const CANCEL_CREATE = 'CANCEL_CREATE'
export const SAVE_CREATE = 'SAVE_CREATE'
export const SAVE_CREATE_SUCCESSFUL = 'SAVE_CREATE_SUCCESSFUL'
export const STACK_CREATE = 'STACK_CREATE'
export const DETAIL_CREATE = 'DETAIL_CREATE'
export const INDEX_CREATE = 'INDEX_CREATE'
export const UPDATE_FORM_STACK_INDEX = 'UPDATE_FORM_STACK_INDEX'
export const VALIDATION_ERROR_CREATE = 'VALIDATION_ERROR_CREATE'

// tooltip

export const FETCH_MODEL_TOOLTIP = 'FETCH_MODEL_TOOLTIP'
export const UPDATE_MODEL_TOOLTIP = 'UPDATE_MODEL_TOOLTIP'

// tableView

export const CHANGE_PAGE = 'CHANGE_PAGE'
export const INDEX_ADD_FILTER = 'INDEX_ADD_FILTER'
export const INDEX_CLEAR_FILTERS = 'INDEX_CLEAR_FILTERS'
export const INDEX_CHANGE_FILTER_FIELD = 'INDEX_CHANGE_FILTER_FIELD'
export const INDEX_DELETE_FILTER = 'INDEX_DELETE_FILTER'
export const INDEX_TABLE_FILTER_CHANGE = 'INDEX_TABLE_FILTER_CHANGE'
export const INDEX_TABLE_FILTER_DROPDOWN = 'INDEX_TABLE_FILTER_DROPDOWN'
export const INDEX_TABLE_FILTER_SUBMIT = 'INDEX_TABLE_FILTER_SUBMIT'
export const INDEX_TABLE_SORT_CHANGE = 'INDEX_TABLE_SORT_CHANGE'
export const COLLAPSE_TABLE_CHANGE = 'COLLAPSE_TABLE_CHANGE'
export const UPDATE_OVERVIEW_DISPLAYED = 'UPDATE_OVERVIEW_DISPLAYED'
export const UPDATE_OVERVIEW_SELECTED = 'UPDATE_OVERVIEW_SELECTED'
export const CHANGE_REL_TABLE_PAGE = 'CHANGE_REL_TABLE_PAGE'

// model

export const FETCH_MODEL_INDEX = 'FETCH_MODEL_INDEX'
export const FETCH_MODEL_DETAIL = 'FETCH_MODEL_DETAIL'
export const UPDATE_MODEL_DETAIL = 'UPDATE_MODEL_DETAIL'
export const UPDATE_MODEL_INDEX = 'UPDATE_MODEL_INDEX'
export const REQUEST_DELETE_MODEL = 'REQUEST_DELETE_MODEL'
export const UPDATE_DELETE_MODEL = 'UPDATE_DELETE_MODEL'
export const REQUEST_DELETE_REL_TABLE_MODEL = 'REQUEST_DELETE_REL_TABLE_MODEL'
export const REQUEST_DELETE_MODEL_FROM_DETAIL_PAGE =
  'REQUEST_DELETE_MODEL_FROM_DETAIL_PAGE'
export const REMOVE_INSTANCE = 'REMOVE_INSTANCE'

// search

export const FETCH_SEARCH_ENTRIES = 'FETCH_SEARCH_ENTRIES'
export const UPDATE_SEARCH_ENTRIES = 'UPDATE_SEARCH_ENTRIES'
export const SEARCH_QUERY_TEXT_CHANGED = 'SEARCH_QUERY_TEXT_CHANGED'
export const SEARCH_QUERY_LINK_CLICKED = 'SEARCH_QUERY_LINK_CLICKED'
export const SEARCH_BLUR = 'SEARCH_BLUR'
export const TRIGGER_SEARCH = 'TRIGGER_SEARCH'

// options

export const DATA_OPTIONS_UPDATE = 'DATA_OPTIONS_UPDATE'
export const EXISTING_VALUE_UPDATE = 'EXISTING_VALUE_UPDATE'
export const MENU_OPEN = 'MENU_OPEN'
export const QUERY_SELECT_MENU_OPEN = 'QUERY_SELECT_MENU_OPEN'
export const RELATIONSHIP_SELECT_MENU_OPEN = 'RELATIONSHIP_SELECT_MENU_OPEN'

// alerts

export const ADD_DANGER_ALERT = 'ADD_DANGER_ALERT'
export const ADD_SUCCESS_ALERT = 'ADD_SUCCESS_ALERT'

// validation

export const SAVE_CREATE_CHECK = 'SAVE_CREATE_CHECK'
export const DETAIL_ATTRIBUTE_EDIT_SUBMIT_CHECK =
  'DETAIL_ATTRIBUTE_EDIT_SUBMIT_CHECK'
export const DETAIL_TABLE_EDIT_SUBMIT_CHECK = 'DETAIL_TABLE_EDIT_SUBMIT_CHECK'
export const INDEX_EDIT_SUBMIT_CHECK = 'INDEX_EDIT_SUBMIT_CHECK'

// misc
export const UNIQUE_CONSTRAINT = 'UNIQUE_CONSTRAINT'
export const INCORRECT_REQUIREMENT_JMET_TYPE = 'INCORRECT_REQUIREMENT_JMET_TYPE'
export const INCORRECT_REQUIREMENT_PARENT_TYPE =
  'INCORRECT_REQUIREMENT_PARENT_TYPE'
export const INCORRECT_DATA_SOURCE_SYSTEM_TYPE =
  'INCORRECT_DATA_SOURCE_SYSTEM_TYPE'

export const CREATE_FILE = 'CREATE_FILE'
export const DELETE_FILE = 'DELETE_FILE'
